"""The evidence key, from configuration to the day the image is gone.

Photo evidence is the most sensitive thing StreakFit stores: an image a
person reported, sealed and kept because a reviewer may need it. The key that
seals it is never generated by the application, never defaulted, and never
stored anywhere the database or this repository can reach.

The gap this file was written for: `photo_evidence.key_id` had been written
at capture since the table existed and read by NOTHING. A rotated or mistyped
key therefore made every stored image permanently unopenable, silently, and
the first person to find out would be a reviewer clicking an image during a
child-safety review.
"""
import uuid
from datetime import datetime, timedelta


import app as appmod
from app import (db, Report, PhotoEvidence, _evidence_cipher, _sweep_moderation_evidence,
                 PHOTO_EVIDENCE_MAX_AGE_DAYS)


KEY_A = "TZTKk2wBhtL8nFVQq0JqkHkGEvkkCMgfPdYzWJXuZ0o="   # test-only Fernet keys
KEY_B = "9Vf0nHgqZ3B2m3DEXKVTNs1mOoVCWpTPZ7Cd4mUOl7Y="


def a_report(**kw):
    kw.setdefault('status', 'pending')
    r = Report(public_id=uuid.uuid4().hex, reporter_user_id=1,
               subject_type='photo', category='child_safety', **kw)
    db.session.add(r)
    db.session.commit()
    return r


def seal(report, key, captured_days_ago=0):
    """Store a real encrypted row under `key`, the way capture does."""
    import os
    old = os.environ.get('STREAKFIT_EVIDENCE_KEY')
    os.environ['STREAKFIT_EVIDENCE_KEY'] = key
    try:
        cipher, key_id = _evidence_cipher()
        assert cipher is not None
        captured = datetime.utcnow() - timedelta(days=captured_days_ago)
        row = PhotoEvidence(
            report_id=report.id, photo_public_id=uuid.uuid4().hex,
            ciphertext=cipher.encrypt(b'\xff\xd8\xff pretend jpeg'),
            content_type='image/jpeg', byte_size=20, key_id=key_id,
            captured_at=captured,
            expires_at=captured + timedelta(days=PHOTO_EVIDENCE_MAX_AGE_DAYS))
        db.session.add(row)
        db.session.commit()
        return row
    finally:
        if old is None:
            os.environ.pop('STREAKFIT_EVIDENCE_KEY', None)
        else:
            os.environ['STREAKFIT_EVIDENCE_KEY'] = old


def checks(client):
    return {c['id']: c for c in
            client.get('/api/verification/self').get_json()['checks']}


# ── Configuration: the app never invents a key ──────────────────────────────

def test_with_no_key_there_is_no_cipher(client, monkeypatch):
    monkeypatch.delenv('STREAKFIT_EVIDENCE_KEY', raising=False)
    assert _evidence_cipher() == (None, None)


def test_a_malformed_key_fails_closed_rather_than_guessing(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', 'not-a-fernet-key')
    assert _evidence_cipher() == (None, None)


def test_the_key_is_never_echoed_into_the_verification_surface(client, monkeypatch):
    """That endpoint is served without a credential."""
    import json
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    blob = json.dumps(client.get('/api/verification/self').get_json())
    assert KEY_A not in blob
    assert KEY_A[:12] not in blob


def test_two_different_keys_have_different_fingerprints(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    _, a = _evidence_cipher()
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_B)
    _, b = _evidence_cipher()

    assert a and b and a != b
    assert KEY_A[:8] not in a and KEY_B[:8] not in b, "fingerprint leaks the key"


# ── Storage is genuinely encrypted ──────────────────────────────────────────

def test_the_stored_bytes_are_not_the_image(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    row = seal(a_report(), KEY_A)

    assert b'pretend jpeg' not in row.ciphertext
    assert not row.ciphertext.startswith(b'\xff\xd8\xff')


def test_the_row_records_which_key_sealed_it(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    _, key_id = _evidence_cipher()
    row = seal(a_report(), KEY_A)
    assert row.key_id == key_id


# ── Rotation: the gap this file exists for ──────────────────────────────────

def test_evidence_sealed_under_a_retired_key_is_reported_not_silent(client, monkeypatch):
    """The check that did not exist. A rotated key used to be invisible."""
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    seal(a_report(), KEY_A)
    assert checks(client)['moderation.evidence_key']['status'] == 'PASS'

    # The operator rotates the key. Every sealed image is now unopenable.
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_B)
    check = checks(client)['moderation.evidence_key']

    assert check['status'] == 'FAIL', check
    assert 'different key' in check['observed']
    assert 'cannot be decrypted' in check['failureReason']


def test_the_key_check_needs_no_plaintext(client, monkeypatch):
    """It compares fingerprints. It must not be decrypting evidence to run."""
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    seal(a_report(), KEY_A)

    called = []
    real = appmod._evidence_cipher

    def spy():
        cipher, kid = real()
        if cipher is not None:
            class NoDecrypt:
                def __getattr__(self, n):
                    if n == 'decrypt':
                        called.append(n)
                        raise AssertionError("the check decrypted evidence")
                    return getattr(cipher, n)
            return NoDecrypt(), kid
        return cipher, kid

    monkeypatch.setattr(appmod, '_evidence_cipher', spy)
    assert checks(client)['moderation.evidence_key']['status'] in ('PASS', 'FAIL')
    assert called == []


def test_with_no_key_the_check_says_nothing_is_being_captured(client, monkeypatch):
    monkeypatch.delenv('STREAKFIT_EVIDENCE_KEY', raising=False)
    check = checks(client)['moderation.evidence_key']

    assert check['status'] == 'UNKNOWN'
    assert 'is being captured' in check['observed']   # "no photo evidence IS BEING CAPTURED"
    assert 'keeps no picture' in check['failureReason']


def test_a_purged_row_does_not_count_against_the_key_check(client, monkeypatch):
    """Deleted evidence is not unreadable evidence; it is gone on purpose."""
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    row = seal(a_report(), KEY_A)
    row.ciphertext, row.purged_at = None, datetime.utcnow()
    db.session.commit()

    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_B)
    assert checks(client)['moderation.evidence_key']['status'] == 'PASS'


# ── Retention and legal hold, for the photo half ────────────────────────────

def test_photo_evidence_is_deleted_not_merely_flagged(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    row = seal(a_report(), KEY_A,
               captured_days_ago=PHOTO_EVIDENCE_MAX_AGE_DAYS + 1)

    _sweep_moderation_evidence()
    db.session.commit()

    assert row.ciphertext is None, "the bytes are still there"
    assert row.byte_size == 0
    assert row.purged_at is not None
    assert row.unavailable_reason == 'retention_expired'


def test_the_row_survives_so_deleted_does_not_read_as_never_captured(client, monkeypatch):
    """Two very different facts about a report, and a reviewer is entitled to
    know which one they are looking at."""
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    r = a_report()
    row = seal(r, KEY_A, captured_days_ago=PHOTO_EVIDENCE_MAX_AGE_DAYS + 1)
    _sweep_moderation_evidence()
    db.session.commit()

    assert db.session.get(PhotoEvidence, row.id) is not None
    assert row.captured_at is not None


def test_a_legal_hold_suppresses_the_photo_purge(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    r = a_report()
    r.legal_hold, r.legal_hold_reason = True, 'court order 123'
    db.session.commit()
    row = seal(r, KEY_A, captured_days_ago=PHOTO_EVIDENCE_MAX_AGE_DAYS + 5)

    result = _sweep_moderation_evidence()
    db.session.commit()

    assert row.ciphertext is not None, "a held image was deleted"
    assert result['held_by_legal_hold'] >= 1


def test_releasing_a_hold_lets_the_next_sweep_delete_it(client, monkeypatch):
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    r = a_report()
    r.legal_hold = True
    db.session.commit()
    row = seal(r, KEY_A, captured_days_ago=PHOTO_EVIDENCE_MAX_AGE_DAYS + 5)
    _sweep_moderation_evidence()
    db.session.commit()
    assert row.ciphertext is not None

    r.legal_hold = False
    db.session.commit()
    _sweep_moderation_evidence()
    db.session.commit()

    assert row.ciphertext is None


def test_expiry_is_measured_from_capture_not_from_closure(client, monkeypatch):
    """Photo bytes are an absolute 30 days. A report left open forever must
    not keep an image forever."""
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', KEY_A)
    r = a_report(status='pending')          # never closed
    row = seal(r, KEY_A, captured_days_ago=PHOTO_EVIDENCE_MAX_AGE_DAYS + 1)

    _sweep_moderation_evidence()
    db.session.commit()

    assert row.ciphertext is None, "an open report kept its image past 30 days"


# ── The fingerprint has to be NAMED, not just compared ─────────────────────

def test_the_check_names_which_key_is_loaded(client, monkeypatch):
    """The gap this closes, found during the Phase B readiness review.

    The check compares stored `photo_evidence.key_id` values against the
    configured key. With ZERO sealed images -- which is production's state at
    first deploy -- there is nothing to compare, so it reported
    `PASS: 0 sealed image(s), all under the current key` and never said WHICH
    key. That is precisely the moment an operator wants to confirm the
    deployed key is the one whose passphrase they hold.

    `key_id` is non-secret by construction: a truncated HMAC of the key under
    a fixed label, enough to tell two keys apart and not enough to be useful
    to anybody.
    """
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode('ascii')
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', key)

    _cipher, expected = appmod._evidence_cipher()
    assert expected, "the app could not fingerprint its own key"

    check = {c['id']: c for c in
             client.get('/api/verification/self').get_json()['checks']
             }['moderation.evidence_key']

    assert check['status'] == 'PASS'
    assert expected in check['observed'], (
        f"the check passed without naming the key it is using; observed: "
        f"{check['observed']!r}")


def test_the_key_itself_never_appears(client, monkeypatch):
    """Naming the fingerprint must not leak the key. /api/verification/self is
    served without a credential."""
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode('ascii')
    monkeypatch.setenv('STREAKFIT_EVIDENCE_KEY', key)

    body = client.get('/api/verification/self').get_data(as_text=True)

    assert key not in body, "the evidence key appeared in an uncredentialed response"
    assert key[:12] not in body, "a prefix of the evidence key appeared"
