"""Age band, guardian links, per-capability consent, permission audit

Revision ID: 08681a9bd9f9
Revises: w7x8y9z0a1b2
Create Date: 2026-09-20 13:27:16.964038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08681a9bd9f9'
down_revision = 'w7x8y9z0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_user_id', sa.Integer(), nullable=False),
    sa.Column('guardian_user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('evidence_ref', sa.String(length=120), nullable=True),
    sa.Column('established_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_user_id', 'guardian_user_id', name='uq_guardian_link')
    )
    with op.batch_alter_table('guardian_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardian_link_child_user_id'), ['child_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardian_link_guardian_user_id'), ['guardian_user_id'], unique=False)

    op.create_table('permission_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_audit_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_audit_subject_user_id'), ['subject_user_id'], unique=False)

    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_user_id', sa.Integer(), nullable=False),
    sa.Column('guardian_link_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guardian_link_id'], ['guardian_link.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_user_id', 'capability', 'guardian_link_id', name='uq_consent')
    )
    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.create_index('ix_consent_child_capability', ['child_user_id', 'capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_child_user_id'), ['child_user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_band', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age_band')

    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_child_user_id'))
        batch_op.drop_index('ix_consent_child_capability')

    op.drop_table('consent')
    with op.batch_alter_table('permission_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_audit_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_permission_audit_occurred_at'))

    op.drop_table('permission_audit')
    with op.batch_alter_table('guardian_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardian_link_guardian_user_id'))
        batch_op.drop_index(batch_op.f('ix_guardian_link_child_user_id'))

    op.drop_table('guardian_link')
    # ### end Alembic commands ###
