"""moderation ops: review deadlines, photo evidence, appeals, retention

Revision ID: 1279c12c6691
Revises: ee93cb7a23d9
Create Date: 2026-09-20 21:10:19.278374

"""
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1279c12c6691'
down_revision = 'ee93cb7a23d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('evidence_kind', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_access_accessed_at'), ['accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_access_report_id'), ['report_id'], unique=False)

    op.create_table('photo_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('photo_public_id', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.Column('unavailable_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_evidence_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_evidence_photo_public_id'), ['photo_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_evidence_report_id'), ['report_id'], unique=False)

    op.create_table('appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['moderation_action.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action_id', name='uq_appeal_user_action')
    )
    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appeal_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeal_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_appeal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeal_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('content_restriction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_restriction_report_id'), ['report_id'], unique=False)
        # Named explicitly: SQLite rebuilds the table for an ALTER and alembic's
        # batch mode refuses an unnamed constraint ('Constraint must have a name').
        batch_op.create_foreign_key('fk_content_restriction_report_id',
                                    'report', ['report_id'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('evidence_purged_at', sa.DateTime(), nullable=True))
        # server_default: existing report rows have no value for a NOT NULL
        # column, and the model default only fires on an ORM insert. Without
        # this the upgrade fails on any database that already has reports.
        batch_op.add_column(sa.Column('legal_hold', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('legal_hold_reason', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_report_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_report_status_due', ['status', 'due_at'], unique=False)

    with op.batch_alter_table('report_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purged_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Backfill review deadlines for reports filed before this milestone.
    #
    # Computed from each report's OWN created_at, not from now: a report that
    # has been waiting two days is already overdue and the queue should say so
    # rather than quietly restarting its clock.
    bind = op.get_bind()
    rows = bind.execute(sa.text(
        "SELECT id, category, created_at FROM report WHERE due_at IS NULL")).fetchall()
    for row_id, category, created_at in rows:
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        hours = 24 if category == 'child_safety' else 72
        bind.execute(
            sa.text("UPDATE report SET due_at = :due WHERE id = :rid"),
            {"due": created_at + timedelta(hours=hours), "rid": row_id})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_evidence', schema=None) as batch_op:
        batch_op.drop_column('purged_at')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index('ix_report_status_due')
        batch_op.drop_index(batch_op.f('ix_report_due_at'))
        batch_op.drop_column('legal_hold_reason')
        batch_op.drop_column('legal_hold')
        batch_op.drop_column('evidence_purged_at')
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('due_at')

    with op.batch_alter_table('content_restriction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_content_restriction_report_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_content_restriction_report_id'))
        batch_op.drop_column('report_id')

    with op.batch_alter_table('appeal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeal_user_id'))
        batch_op.drop_index(batch_op.f('ix_appeal_status'))
        batch_op.drop_index(batch_op.f('ix_appeal_public_id'))
        batch_op.drop_index(batch_op.f('ix_appeal_action_id'))

    op.drop_table('appeal')
    with op.batch_alter_table('photo_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_evidence_report_id'))
        batch_op.drop_index(batch_op.f('ix_photo_evidence_photo_public_id'))
        batch_op.drop_index(batch_op.f('ix_photo_evidence_expires_at'))

    op.drop_table('photo_evidence')
    with op.batch_alter_table('evidence_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_access_report_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_access_accessed_at'))

    op.drop_table('evidence_access')
    # ### end Alembic commands ###
