"""moderation notices: noticing a review obligation exactly once

No backfill, deliberately. The generator is idempotent and derives its rows
from live state -- the first sweep after this migration notices every report
that is already urgent or already overdue, and the unique constraint keeps it
to one row each. Backfilling here would duplicate that work and would have to
guess a created_at it cannot know.

Revision ID: 476bd58c9925
Revises: 1279c12c6691
Create Date: 2026-09-21 06:22:19.429161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476bd58c9925'
down_revision = '1279c12c6691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_ref', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_ref', 'kind', name='uq_moderation_notice_subject_kind')
    )
    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_notice_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_notice_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_notice_subject_ref'), ['subject_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_notice_subject_ref'))
        batch_op.drop_index(batch_op.f('ix_moderation_notice_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_moderation_notice_created_at'))

    op.drop_table('moderation_notice')
    # ### end Alembic commands ###
