"""notice leases and a record that delivery ran

Revision ID: 47f7dc9962e3
Revises: c50e9d7b2fd8
Create Date: 2026-09-21 09:50:39.064591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f7dc9962e3'
down_revision = 'c50e9d7b2fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_run_ran_at'), ['ran_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_run_source'), ['source'], unique=False)

    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('claimed_by', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('provider_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_moderation_notice_claimed_at'), ['claimed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_notice_claimed_at'))
        batch_op.drop_column('provider_key')
        batch_op.drop_column('claimed_by')
        batch_op.drop_column('claimed_at')

    with op.batch_alter_table('notification_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_run_source'))
        batch_op.drop_index(batch_op.f('ix_notification_run_ran_at'))

    op.drop_table('notification_run')
    # ### end Alembic commands ###
