"""retention runs know which promise, notices know their delivery

No backfill, and the server_defaults are doing that work on purpose.

Every retention_run row that existed before this migration was a coach sweep,
because the coach sweep was the only thing that wrote one. `kind` defaults to
'coach' at the database level so those rows keep exactly the meaning they had
-- an UPDATE would say the same thing more slowly and could be interrupted
halfway.

`outcome` defaults to 'ok' for the same reason: a row that was written at all
was written by a sweep that completed, since the success record has always
been added in the same transaction as the deletions.

Notices default to zero attempts. A notice generated before delivery existed
has genuinely never been attempted, so zero is true rather than convenient.


Revision ID: c50e9d7b2fd8
Revises: 476bd58c9925
Create Date: 2026-09-21 07:27:36.488916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e9d7b2fd8'
down_revision = '476bd58c9925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_moderation_notice_last_attempt_at'), ['last_attempt_at'], unique=False)

    with op.batch_alter_table('retention_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='coach', nullable=False))
        batch_op.add_column(sa.Column('outcome', sa.String(length=16), server_default='ok', nullable=False))
        batch_op.add_column(sa.Column('error_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_retention_run_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retention_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_run_kind'))
        batch_op.drop_column('detail')
        batch_op.drop_column('error_type')
        batch_op.drop_column('outcome')
        batch_op.drop_column('kind')

    with op.batch_alter_table('moderation_notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_notice_last_attempt_at'))
        batch_op.drop_column('last_error')
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('attempts')
        batch_op.drop_column('receipt')

    # ### end Alembic commands ###
