"""moderation: blocks, reports, evidence, actions, restrictions

Revision ID: ee93cb7a23d9
Revises: 08681a9bd9f9
Create Date: 2026-09-20 19:50:08.030241

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee93cb7a23d9'
down_revision = '08681a9bd9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lifted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_restriction', schema=None) as batch_op:
        batch_op.create_index('ix_content_restriction_subject', ['subject_type', 'subject_ref'], unique=False)

    op.create_table('user_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name='uq_user_block')
    )
    with op.batch_alter_table('user_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_block_blocked_user_id'), ['blocked_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_block_blocker_user_id'), ['blocker_user_id'], unique=False)

    op.create_table('user_restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_restriction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_restriction_user_id'), ['user_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('disposition', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)
        batch_op.create_index('ix_report_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_team_id'), ['team_id'], unique=False)

    op.create_table('moderation_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_action_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_action_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('report_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_evidence_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('team_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_team_message_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###

    # Backfill: give every message that already exists a reportable handle.
    #
    # The column default only fires on INSERT, so without this every message
    # written before today would be unreportable -- and the messages most
    # likely to need reporting are the ones already sitting in a thread.
    #
    # One UPDATE per row rather than a single SQL expression, because the id
    # has to be unique and neither SQLite nor Postgres offers a portable
    # per-row random hex. Threads are small; this is bounded by the number of
    # messages that exist, which today is tens.
    bind = op.get_bind()
    rows = bind.execute(sa.text(
        "SELECT id FROM team_message WHERE public_id IS NULL")).fetchall()
    for (row_id,) in rows:
        bind.execute(
            sa.text("UPDATE team_message SET public_id = :pid WHERE id = :rid"),
            {"pid": uuid.uuid4().hex, "rid": row_id})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_message_public_id'))
        batch_op.drop_column('public_id')

    with op.batch_alter_table('report_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_evidence_report_id'))

    op.drop_table('report_evidence')
    with op.batch_alter_table('moderation_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_action_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_action_report_id'))

    op.drop_table('moderation_action')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_team_id'))
        batch_op.drop_index('ix_report_status_created')
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_public_id'))

    op.drop_table('report')
    with op.batch_alter_table('user_restriction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_restriction_user_id'))

    op.drop_table('user_restriction')
    with op.batch_alter_table('user_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_block_blocker_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_block_blocked_user_id'))

    op.drop_table('user_block')
    with op.batch_alter_table('content_restriction', schema=None) as batch_op:
        batch_op.drop_index('ix_content_restriction_subject')

    op.drop_table('content_restriction')
    # ### end Alembic commands ###
